USE [master]
GO

/****** Object:  Database [Hotelprojekt]    Script Date: 14.04.2023 14:19:44 ******/
CREATE DATABASE [Hotelprojekt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hotelprojekt', FILENAME = N'C:\SQL-Kurs\DB\Hotelprojekt.mdf' , 
	SIZE = 65536KB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Hotelprojekt_log', FILENAME = N'C:\SQL-Kurs\DB\Hotelprojekt_log.ldf' , 
	SIZE = 1536KB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hotelprojekt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hotelprojekt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hotelprojekt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hotelprojekt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hotelprojekt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hotelprojekt] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hotelprojekt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hotelprojekt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hotelprojekt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hotelprojekt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hotelprojekt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hotelprojekt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hotelprojekt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hotelprojekt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hotelprojekt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hotelprojekt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hotelprojekt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hotelprojekt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hotelprojekt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hotelprojekt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hotelprojekt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hotelprojekt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hotelprojekt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hotelprojekt] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Hotelprojekt] SET  MULTI_USER 
GO

ALTER DATABASE [Hotelprojekt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hotelprojekt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hotelprojekt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hotelprojekt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hotelprojekt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hotelprojekt] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Hotelprojekt] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Hotelprojekt] SET  READ_WRITE 
GO


